In [ ]:
import sys
import os

# Project root
if os.getcwd().endswith("Notebooks"):
    os.chdir("..")

# Adding the root path to Python path
sys.path.append(os.getcwd())

In [13]:
from Preprocessing_package.extract_artist_name import create_image_artist_df

df = create_image_artist_df()
df.head(5)

                                          image_path  artist_name
0  raw_data/images/images/Edgar_Degas/Edgar_Degas...  Edgar Degas
1  raw_data/images/images/Edgar_Degas/Edgar_Degas...  Edgar Degas
2  raw_data/images/images/Edgar_Degas/Edgar_Degas...  Edgar Degas
3  raw_data/images/images/Edgar_Degas/Edgar_Degas...  Edgar Degas
4  raw_data/images/images/Edgar_Degas/Edgar_Degas...  Edgar Degas

In [6]:
import pandas as pd

In [15]:
# Load the artists.csv metadata
artists_df = pd.read_csv("raw_data/artists.csv")

# make names lowercase
artists_df["name_clean"] = artists_df["name"].str.lower()
df["artist_name_clean"] = df["artist_name"].str.lower()

# Join on cleaned names
merged_df = df.merge(artists_df, left_on="artist_name_clean", right_on="name_clean", how="left")
print(merged_df.head(5))

                                          image_path  artist_name  \
0  raw_data/images/images/Edgar_Degas/Edgar_Degas...  Edgar Degas
1  raw_data/images/images/Edgar_Degas/Edgar_Degas...  Edgar Degas
2  raw_data/images/images/Edgar_Degas/Edgar_Degas...  Edgar Degas
3  raw_data/images/images/Edgar_Degas/Edgar_Degas...  Edgar Degas
4  raw_data/images/images/Edgar_Degas/Edgar_Degas...  Edgar Degas

  artist_name_clean  id         name        years          genre nationality  \
0       edgar degas  30  Edgar Degas  1834 - 1917  Impressionism      French
1       edgar degas  30  Edgar Degas  1834 - 1917  Impressionism      French
2       edgar degas  30  Edgar Degas  1834 - 1917  Impressionism      French
3       edgar degas  30  Edgar Degas  1834 - 1917  Impressionism      French
4       edgar degas  30  Edgar Degas  1834 - 1917  Impressionism      French

                                                 bio  \
0  Edgar Degas (US:  or UK: ; born Hilaire-Germai...
1  Edgar Degas (US:  or UK: ; born Hilaire-Germai...
2  Edgar Degas (US:  or UK: ; born Hilaire-Germai...
3  Edgar Degas (US:  or UK: ; born Hilaire-Germai...
4  Edgar Degas (US:  or UK: ; born Hilaire-Germai...

                                  wikipedia  paintings   name_clean
0  http://en.wikipedia.org/wiki/Edgar_Degas        702  edgar degas
1  http://en.wikipedia.org/wiki/Edgar_Degas        702  edgar degas
2  http://en.wikipedia.org/wiki/Edgar_Degas        702  edgar degas
3  http://en.wikipedia.org/wiki/Edgar_Degas        702  edgar degas
4  http://en.wikipedia.org/wiki/Edgar_Degas        702  edgar degas

In [8]:
# Save the result to CSV
df.to_csv("raw_data/image_artist_mapping.csv", index=False)

In [9]:
# clean the double images

df["image_path"] = df["image_path"].str.replace("images/images", "images", regex=False)

In [12]:
df

,image_path,artist_name,artist_name_clean
0,raw_data/images/Edgar_Degas/Edgar_Degas_27.jpg,Edgar Degas,edgar degas
1,raw_data/images/Edgar_Degas/Edgar_Degas_199.jpg,Edgar Degas,edgar degas
2,raw_data/images/Edgar_Degas/Edgar_Degas_428.jpg,Edgar Degas,edgar degas
3,raw_data/images/Edgar_Degas/Edgar_Degas_240.jpg,Edgar Degas,edgar degas
4,raw_data/images/Edgar_Degas/Edgar_Degas_257.jpg,Edgar Degas,edgar degas
...,...,...,...
7696,raw_data/images/Leonardo_da_Vinci/Leonardo_da_...,Leonardo da Vinci,leonardo da vinci
7697,raw_data/images/Leonardo_da_Vinci/Leonardo_da_...,Leonardo da Vinci,leonardo da vinci
7698,raw_data/images/Leonardo_da_Vinci/Leonardo_da_...,Leonardo da Vinci,leonardo da vinci
7699,raw_data/images/Leonardo_da_Vinci/Leonardo_da_...,Leonardo da Vinci,leonardo da vinci
7700,raw_data/images/Leonardo_da_Vinci/Leonardo_da_...,Leonardo da Vinci,leonardo da vinci