In [7]:
import sys
import os

# Project root
if os.getcwd().endswith("notebooks"):
    os.chdir("..")

# Adding the root path to Python path
sys.path.append(os.getcwd())

In [8]:
from preprocessing_package.extract_artist_name import create_image_artist_df

df = create_image_artist_df()
df.head(5)

                                          image_path    artist_name
0  raw_data/images/Piet_Mondrian/Piet_Mondrian_38...  Piet Mondrian
1  raw_data/images/Piet_Mondrian/Piet_Mondrian_10...  Piet Mondrian
2  raw_data/images/Piet_Mondrian/Piet_Mondrian_11...  Piet Mondrian
3  raw_data/images/Piet_Mondrian/Piet_Mondrian_39...  Piet Mondrian
4  raw_data/images/Piet_Mondrian/Piet_Mondrian_13...  Piet Mondrian

In [11]:
import pandas as pd

In [12]:
# Load the artists.csv metadata
artists_df = pd.read_csv("raw_data/artists.csv")

# make names lowercase
artists_df["name_clean"] = artists_df["name"].str.lower()
df["artist_name_clean"] = df["artist_name"].str.lower()

# Join on cleaned names
merged_df = df.merge(artists_df, left_on="artist_name_clean", right_on="name_clean", how="left")
print(merged_df.head(5))

                                          image_path    artist_name  \
0  raw_data/images/Piet_Mondrian/Piet_Mondrian_38...  Piet Mondrian
1  raw_data/images/Piet_Mondrian/Piet_Mondrian_10...  Piet Mondrian
2  raw_data/images/Piet_Mondrian/Piet_Mondrian_11...  Piet Mondrian
3  raw_data/images/Piet_Mondrian/Piet_Mondrian_39...  Piet Mondrian
4  raw_data/images/Piet_Mondrian/Piet_Mondrian_13...  Piet Mondrian

  artist_name_clean  id           name        years          genre  \
0     piet mondrian  43  Piet Mondrian  1872 – 1944  Neoplasticism
1     piet mondrian  43  Piet Mondrian  1872 – 1944  Neoplasticism
2     piet mondrian  43  Piet Mondrian  1872 – 1944  Neoplasticism
3     piet mondrian  43  Piet Mondrian  1872 – 1944  Neoplasticism
4     piet mondrian  43  Piet Mondrian  1872 – 1944  Neoplasticism

  nationality                                                bio  \
0       Dutch  Pieter Cornelis Mondriaan, after 1906 Piet Mon...
1       Dutch  Pieter Cornelis Mondriaan, after 1906 Piet Mon...
2       Dutch  Pieter Cornelis Mondriaan, after 1906 Piet Mon...
3       Dutch  Pieter Cornelis Mondriaan, after 1906 Piet Mon...
4       Dutch  Pieter Cornelis Mondriaan, after 1906 Piet Mon...

                                     wikipedia  paintings     name_clean
0  https://en.wikipedia.org/wiki/Piet_Mondrian         84  piet mondrian
1  https://en.wikipedia.org/wiki/Piet_Mondrian         84  piet mondrian
2  https://en.wikipedia.org/wiki/Piet_Mondrian         84  piet mondrian
3  https://en.wikipedia.org/wiki/Piet_Mondrian         84  piet mondrian
4  https://en.wikipedia.org/wiki/Piet_Mondrian         84  piet mondrian

In [13]:
# Save the result to CSV
df.to_csv("raw_data/image_artist_mapping.csv", index=False)

In [15]:
df

,image_path,artist_name,artist_name_clean
0,raw_data/images/Piet_Mondrian/Piet_Mondrian_38...,Piet Mondrian,piet mondrian
1,raw_data/images/Piet_Mondrian/Piet_Mondrian_10...,Piet Mondrian,piet mondrian
2,raw_data/images/Piet_Mondrian/Piet_Mondrian_11...,Piet Mondrian,piet mondrian
3,raw_data/images/Piet_Mondrian/Piet_Mondrian_39...,Piet Mondrian,piet mondrian
4,raw_data/images/Piet_Mondrian/Piet_Mondrian_13...,Piet Mondrian,piet mondrian
...,...,...,...
7696,raw_data/images/William_Turner/William_Turner_...,William Turner,william turner
7697,raw_data/images/William_Turner/William_Turner_...,William Turner,william turner
7698,raw_data/images/William_Turner/William_Turner_...,William Turner,william turner
7699,raw_data/images/William_Turner/William_Turner_...,William Turner,william turner
7700,raw_data/images/William_Turner/William_Turner_...,William Turner,william turner